//AL: Define your actionType here

export enum ActionType {
  GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS",
  ADD_PRODUCT = "ADD_PRODUCT",
  GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS",
  UPDATE_RENDER = "UPDATE_RENDER",
  SEARCH_PRODUCTS = "SEARCH_PRODUCTS",
  SORT_PRODUCTS = "SORT_PRODUCTS",
  FILTER_PRODUCTS = "FILTER_PRODUCTS",
  ADMIN_LOGIN = "ADMIN_LOGIN",
  ADD_CHECKOUT = "ADD_CHECKOUT",
  REMOVE_CHECKOUT = "REMOVE_CHECKOUT",
  GET_ALL_USERS = "GET_ALL_USERS",
  GET_TOKEN_USER_LOG = "GET_TOKEN_USER_LOG",
  GET_ALL_ORDERS = "GET_ALL_ORDERS",
  GET_ORDER_BY_ID = "GET_ORDER_BY_ID"
}
