//AL: Define your actionType here

export enum ActionType {
  GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS",
  ADD_PRODUCT = "ADD_PRODUCT",
  GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS",
  UPDATE_RENDER = "UPDATE_RENDER",
  SEARCH_PRODUCTS = "SEARCH_PRODUCTS",
  SORT_PRODUCTS = "SORT_PRODUCTS",
  FILTER_PRODUCTS = "FILTER_PRODUCTS",
  ADMIN_LOGIN = "ADMIN_LOGIN",
}
